### ISSUE TITLE
[Question] Deploy Cpanel Hook for Wildcard Domains

### ISSUE THREAD

**Issue by 0reo27** [acmesh-official/acme.sh#1642]
Is there any way to deploy a wildcard cert using --deploy --deploy-hook cpanel_uapi?

**Comment by dannytix** [comment]
I know this is old, but since it is still open and one of the top results for these keywords I think it's worth adding some info to guide others with this problem.

To deploy the certificate, I had to make a symbolic link in my .acme.sh folder with the name of my main cpanel site (e.g. example.com) from the *.example.com directory acme.sh created for my certificate, as well as links for most of the files in the *.example.com folder. After that you can issue a deploy command for example.com that will use the *.example.com certificate, but if you have any other subdomains to deploy against, you will need to manually copy the certificate to each in CPanel (or use a script like the one in issue [2992](https://github.com/acmesh-official/acme.sh/issues/2992).

I have created a patch that addresses this, currently pending review under pull request [4256](https://github.com/acmesh-official/acme.sh/pull/4256), which I encourage everyone in the same situation to check out.
