### ISSUE TITLE
post-hook and renew-hook don't run in cron mode

### ISSUE THREAD

**Issue by gabrielcossette** [acmesh-official/acme.sh#2865]
Hi,

Using `--cron` mode, `--post-hook` and `--renew-hook` don't run.

Thanks for looking into it!

**Comment by gabrielcossette** [comment]
I am using the latest code indeed.

**Comment by Neilpang** [comment]
it doesn't work with "--cron".

https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',--'--post-hook',-'---renew-hook'-and-'---reloadcmd'

**Comment by gabrielcossette** [comment]
Apologies, didn't see the page. Thanks!

**Comment by emvidi** [comment]
The above link does not work because it misses a single qoute ate the end
[https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',--'--post-hook',-'---renew-hook'-and-'---reloadcmd'](https://github.com/acmesh-official/acme.sh/wiki/Using-'--pre-hook',--'--post-hook',-'---renew-hook'-and-'---reloadcmd')
