### ISSUE TITLE
Please clarify "Webroot mode" in the README

### ISSUE THREAD

**Issue by dandv** [acmesh-official/acme.sh#2953]
Steps [6](https://github.com/acmesh-official/acme.sh#6-use-apache-mode) and 7 refer to a "`Webroot mode`". What mode is that? Can they link to it instead? The word "Webroot" only appears under [Supported modes](https://github.com/acmesh-official/acme.sh#supported-modes) but is not explained. There is no heading called "Webroot mode" (or "Web root mode").

Also, Step 6 and Step 7 say

> If you are running a web server, Apache or Nginx, it is recommended to use the `Webroot mode`.

So Step 6/7 basically says, do not run in this Step 6/7 mode, but run in this "`Webroot mode`" (which we don't link to)? I'm confused.

But the next sentence is,

> Particularly, if you are running an nginx server, you can use nginx mode instead.

???

**Comment by Neilpang** [comment]
readme is updated.
And webroot mode is `-w` mode.
https://github.com/acmesh-official/acme.sh#2-just-issue-a-cert

**Comment by suguruwataru** [comment]
>  webroot mode is `-w` mode

Okay, what is `-w` mode then? `-w` is even less descriptive than the word "webroot".
Not just "webroot mode" but every time the word "mode" appears in this project's documentation I feel frustrated. Those mode names are not standard terms, but they appear every where in the documentation without definitions given, so I have no idea what the script does in one mode and how it is different from the other. Like, we have the "standalone" mode. What does the word "standalone" even mean here? What is it like if it's not standalone? Why does the standalone mode need an extra dependency, which makes it seem less standalone?

**Comment by dandv** [comment]
@suguruwataru, did you leave a comment here?

**Comment by suguruwataru** [comment]
@dandv Yeah I got kinda upset yesterday and sort of ranted about how the modes are not defined in the docs while not being standard terms. I immediately found a page that was a somewhat okay description of the standalone mode after posting the comment. Then I thought I shouldn't rant about a free project so deleted it.

**Comment by dandv** [comment]
@suguruwataru maybe your feedback could actually be useful to improve the project?

**Comment by suguruwataru** [comment]
Well, sure, my complaint was that the term "mode" was kind of abused in this project's documentation. They appear very early in the online docs and in the `--help` docs, and are used throughout all docs, but lack definition. 

Obviously, either "webroot mode" or "standalone mode" mean a whole set of behaviors, and a user will want to know all the details so that they don't footgun themselves (footguns appear way too frequently when setting up a website), but I didn't find a centralized place that lists the behaviors so that one can easily learn and refer to.

@dandv thank you for bringing me back to this. I do appreciate the attitude that we can all do something good, even as small as leaving a feedback. And the fact that I spent 2 weeks to get myself motivated enough to leave this comment also tells that open source developer are really great people and we should treat them well...
