### ISSUE TITLE
Add Dynadot Api support

### ISSUE THREAD

**Issue by zqs125** [acmesh-official/acme.sh#3419]
Hello, can you add Dynadot Api support? Api document address: https://www.dynadot.com/domain/api3.html

**Comment by Neilpang** [comment]
I don't find the api to add and remove txt records.

**Comment by zqs125** [comment]
Can these two commands be completed：
1、set_dns2   https://www.dynadot.com/domain/api3.html#set_dns2
2、set_clear_domain_setting   https://www.dynadot.com/domain/api3.html#set_clear_domain_setting

**Comment by Neilpang** [comment]
set_dns2 can only SET a record,  we need to ADD 2 txt records for the same sub domain:  sub.example.com

set_clear_domain_setting can not clear a specified TXT record.

**Comment by zqs125** [comment]
I consulted customer service. The set_clear_domain_setting command can delete TXT records

Dynadot10:00pm
Yes, the set_clear_domain_setting command will clear the TXT records if your have configured for your domain.

**Comment by HRHDaniel** [comment]
@Neilpang I did get this working - basically I call "get_dns" to retrieve the entire config for the domain, add the subdomain/challenge, then call "set_dns2" with that full config.  Their APIs are a bit of a pain in that they respond with json - but they take in URL params, and the names and structures don't match.  I used `jq` to process the json response and together with `sed` create the URL params needed.  However, the Github actions for the tests are failing, I believe the test environments don't have `jq` installed, so I haven't created a PR.  It looks like several of the deploy plugins use `jq`, so is this something we can add for use in the dns plugins?

@zqs125 if you have `jq` installed or can install it you can pull my dynadot implementation into your installed instance:
https://github.com/HRHDaniel/acme.sh/blob/master/dnsapi/dns_dynadot.sh

**Comment by working-name** [comment]
@Neilpang  `set_dns2` command as they call it is a whole-zone replacement - if you set a single "a" record, everything else gets deleted and it will have that lone a record.

So instead of thinking about removing and adding a txt record, you basically have to think local mapping, then one API call to overwrite the target domain's whole zone, with the right txt record:

1. pull the existing records for the domain using `list_domain` command
2. parse return to isolate the target domain (because all domains in the account are listed regardless of you specifying a domain in the `list_domain` request)
3. map existing records to the variable names expected by `set_dns2` and omit or replace values for the txt record in question.
4. Note or state the limitation of _20 main_ DNS records as `set_dns2` is limited to `main_recordx0 - main_recordx19`, and _100 subdomain_ DNS records `subdomain0 - subdomain99`

It can be done in bash but it's a veritable PITA for sure. This is very close to the worst possible API implementation I've ever seen in my life.
