### ISSUE TITLE
$ signs not escaped when retrieving password from deploy conf file

### ISSUE THREAD

**Issue by DavidW250** [acmesh-official/acme.sh#3421]
I deploy certificates on a Synology NAS using the synology_dsm deploy hook.  The hook calls _getdeployconf() to retrieve the admin password stored in the deploy configuration file:

_getdeployconf SYNO_Password

_getdeployconf is not properly escaping '$' symbols when it retrieves SAVED_SYNO_Password from the config file and the '$' plus the following character are being stripped from the password.

**Comment by Run-King** [comment]
I just ran into this issue as well.
It seems this can be fixed by replacing line https://github.com/acmesh-official/acme.sh/blob/master/acme.sh#L2269
`  eval "export $_rac_key=\"$_saved\""`
with
`  eval "export $_rac_key=\"\$_saved\""`
This way the _saved variable will be evaluated instead if it's value.

**Comment by DavidW250** [comment]
Thank you Run-King.  Although I could figure out where the problem was, I wasn't knowledgeable enough to figure out how to fix it without potentially breaking something.
