### ISSUE TITLE
specifying '--days 365' does nothing

### ISSUE THREAD

**Issue by Teknoenie** [acmesh-official/acme.sh#3473]
Steps to reproduce
------------------
```
/root/.acme.sh/acme.sh --issue -d example.com -d '*.example.com' --days 365 --force
openssl x509 -noout -text -in example.com/fullchain.cer  |grep After
            Not After : Jul  5 08:28:19 2021 GMT
```
Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by greecemunky** [comment]
If your intention is to create a 365-day certificate, you cannot.  LetsEncrypt by design issues certificates valid for 90 days.  See [here](https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid) for more information.

```--days``` is used to override the default frequency of automatically renewing certificates, which is currently 60 days (so there is a 30-day buffer).  Setting this value to 365 will result in your certificate expiring, as there would be ~275 days remaining until it next attempts to renew.

**Comment by TiloGit** [comment]
Paid ZERO SSL supports 365 days / 1 year certs. Can I use `--days` for that way?

**Comment by TiloGit** [comment]
fyi, trying: 
```shell
acme.sh --server zerossl  --issue  --standalone -d  tilo.mydom123.com  --valid-to  "+365d"		
```
doesn't work get response 
```json
{
    "detail": "No suitable certificate product is currently available to this account",
    "status": 401,
    "type": "urn:ietf:params:acme:error:unauthorized"
}
```
