### ISSUE TITLE
Changing the default server to ZeroSSL broke my site

### ISSUE THREAD

**Issue by realulim** [acmesh-official/acme.sh#3633]
This is just to notify the developers that this change broke my live site.

Its letsencrypt certificate expired and acme.sh couldn't renew it. Upon checking why the renewal didn't work I found that I had to upgrade acme.sh (error: could not get nonce) and after I upgraded I got "Can not init api, for https://acme-v01.api.letsencrypt.org/directory" and so I had to create new certificates to get to the acme-v02 server and then I got "acme.sh is using ZeroSSL as default CA now. Please update your account with an email address first."

I had never heard of ZeroSSL and thus no idea if that CA could be trusted and what the repercussions would be to register my email address. So I had to start reading docs etc. in order to find out how to keep on using letsencrypt until I get up to speed with ZeroSSL. When the dust settled I had incurred a relevant downtime going through the entire process.

The main problem is that acme.sh broke and that no bugfix release was supplied. Instead I had to upgrade to a new major version in order to get the fix. But then I had to additionally deal with the backwards incompatible changes in the major version.

You can close this issue after acknowledging it. Nothing can be done now, but perhaps these changes can be handled better in the future.

**Comment by Neilpang** [comment]
It seems you upgraded from a very early version to the latest version.

There was a bug for upgrading from a very early version directly to the latest version.

you can use `--set-default-ca  --server letsencrypt` to stick to use letsencrypt.

https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL

It is recommended to enabled auto upgrade, so that acme.sh can get latest fixes.
