### ISSUE TITLE
acme certificate fails to verify on zimbra zmcertmgr

### ISSUE THREAD

**Issue by rfc4711** [acmesh-official/acme.sh#3761]
Steps to reproduce
------------------
1) get the certificate with acme.sh 
2) validate or try to load the certificate into zimbra 8.8

Certificates check out good witn openssl verify and verifying on zimbra without fullchain. However, no matter what ISRG Cert I add to fullchain or even changing the acme.sh script with "DEFAULT_CA=$CA_LETSENCRYPT_V2"  the validation for the ISRG Root X1 fails. 

Debug log:
-----------------

```
zimbra@chatter:~/ssl/acme$ zmcertmgr verifycrt comm  ./chatter.net.key.pem chatter.net.cert.pem chatter.net.fullchain.pem 
** Verifying 'chatter.net.cert.pem' against './chatter.net.key.pem'
Certificate 'chatter.net.cert.pem' and private key './chatter.net.key.pem' match.
** Verifying 'chatter.net.cert.pem' against 'chatter.net.fullchain.pem'
ERROR: Unable to validate certificate chain: C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate
error chatter.net.cert.pem: verification failed
```

**Comment by JimDunphy** [comment]
I think the issue seems to be on new installs of acme.sh which might be a documentation issue.  This is repeatable with v3.0.1

1) install clean acme.sh
2) ./acme.sh --set-default-ca --preferred-chain "ISRG" --server letsencrypt
3) issue a certificate (don't specify --preferred-chain)
4) observe that fullchain.cer has 3 certificates present

The issue of a first certificate is a little confusing for someone attempting to use acme.sh on clean install with zimbra since they require the chain to be validated with openssl before it can be installed. The workaround is to issue the certificate a second time by either the method you showed above with --set-default-chain or to specify the --preferred-chain on that initial certificate issue the first time.

Is that the desired outcome for clean installs of acme.sh that know they want the ISRG X1 chain on first certificate issue? Perhaps --preferred-chain only applies to the per certificate config file. I think I thought that step 2 above was setting up my preference for preferred-chain but I don't see any way for you to save that in account.conf now that observed the above behavior.

Jim

**Comment by JimDunphy** [comment]
New installs.... --upgrade

**Comment by JimDunphy** [comment]
not enough detail in my previous comment. I can only reproduce this with a clean/new install just as I showed.  Don't know why but others have been reporting this exactly until I tried the new/clean install to verify the claims. If you are --upgrade then it isn't a new/clean install.

Hope this helps.

Jim
