### ISSUE TITLE
acme.sh --list shows wrong default CA server

### ISSUE THREAD

**Issue by z0rti** [acmesh-official/acme.sh#4445]
After updating to 3.0.5 i see 'CA ZeroSSL.com' in 'acme.sh --list' output
and when i renewed a cert it actually uses ZeroSSL, so i did
```acme.sh --set-default-ca --server letsencrypt```
but in  'acme.sh --list' it still says 'CA ZeroSSL.com'
then i renewed the cert again, now it uses LE, and --list shows 'CA LetsEncrypt.org' as it should

so it's just optics (but confusing)

**Comment by PMExtra** [comment]
`acme.sh --list` shows the certificates with current issuer CA. It may not be same as the default CA.
If you want to change the CA of an already issued domain, you may need to issue again with `--server` argument.

**Comment by nwsw** [comment]
Based on my short review of `acme.sh`, the clearest fix would be to either:

- set a proper default for `Le_API` in the `_initpath()` function, or
- use a proper default in the `_getCAShortName()` function

The source of the problem is that each `host.conf` file is missing the new `Le_API` config assignment, and the `Le_API` variable is left undefined in the `acme.sh` script, so the following loop ends up incorrectly displaying `DEFAULT_CA` for old conf files:

```bash
        DOMAIN_CONF="$di/$d.conf"
        if [ -f "$DOMAIN_CONF" ]; then
          . "$DOMAIN_CONF"
          _ca="$(_getCAShortName "$Le_API")"
          if [ -z "$_domain" ]; then
            printf "%s\n" "$Le_Domain${_sep}\"$Le_Keylength\"${_sep}$Le_Alt${_sep}$_ca${_sep}$Le_CertCreateTimeStr${_sep}$Le_NextRenewTimeStr"
          else
            if [ "$_domain" = "$d" ]; then
              cat "$DOMAIN_CONF"
            fi
          fi
        fi
```

**Comment by Neilpang** [comment]
fixed,  try again with the latest dev

```
acme.sh --upgrade  -b dev
```
