### ISSUE TITLE
About HiCA exploiting RCE vulnerability

### ISSUE THREAD

**Issue by BeSafee** [acmesh-official/acme.sh#4668]
https://patents.google.com/patent/CN115277183A/en
https://patents.google.com/patent/CN114677136A/en

These are the two patents found. Judging from these two patents, `Shanghai Dixi Technology Co ltd` has discovered this RCE vulnerability at least before March 2022, but it did not report it to the community, but used this vulnerability for business Activity (display payment QR code, think so for now).
Confusingly, they donated $1000 to acme.sh in 2022. （[see here](https://github.com/acmesh-official/acme.sh/issues/4659#issuecomment-1584414218)）
So it is puzzling whether this vulnerability is intentionally not fixed.
As of now, this vulnerability has no CVE ID, and how many clients are still affected by this?
Should know that although HiCA shuts down the server, the entities associated with HiCA also include [Digitalsign](https://www.ssls.com.cn), [Quantum CA](https://www.quantumca.com.cn) [tokenssL](https://github.com/tokenssL), etc. Are these entities still exploiting this vulnerability?

**Comment by xiaohuilam** [comment]
This is not associated topic to RCE.
Again, RCE is only utilized to complete challenge response without CA grant our server the ACME abilities.

If you are interested you may invest some programming resources to try to implement your owned domain ACME server, with a CA’s API.

Because acme tools only write challenge file into /.well-known/acme-challenge/ and It’s not possible if don’t output file into the /.well-known/pki-validation/ directory CA required. The only way we find is this. 

and further topic, acme has more differences than normal CA require:
- acme requires CSR submission in finalize, but traditional CA requires in new-order
- acme write challenge file to  /.well-known/acme-challenge/ and traditional CA write in to /.well-known/pki-validation/
- acme the dns validation hostname is _acme-challange constantly, traditional CA is _<md5> or _dnsauth (ssl.com, sectigo and DigiCert, GlobalSign).

After we utilized this goal we think it must be valuable, the patents including is applied due to the lack security awareness of our team at that time. We don’t know this is RCE we only know it can be utilized to make traditional CA ssl enroll process possible in a famous ACME tool. 

About the donation, a correction it is 1100 $ USD donation, it is only our enthusiasm to acme.sh community, we donate it because we think it’s perfect tool it supports most dns providers in the world. No others have even certbot. And 100% certainly they have no associated with this RCE issue even they don’t know the method we utilized when donation happen.

I suggest you do less Irresponsible to blame an open source community

**Comment by BeSafee** [comment]
> I suggest you do less Irresponsible to blame an open source community

I'm just raising my concerns, not blaming anyone.
You also said that you are not a CA organization, but "hijacked" the interaction between the user and the CA, and injected the code executed on the client to complete the entire process. This process looks to the user as if it complies with the ACME protocol.

**Comment by xiaohuilam** [comment]
> > I suggest you do less Irresponsible to blame an open source community
> 
> I'm just raising my concerns, not blaming anyone. You also said that you are not a CA organization, but "hijacked" the interaction between the user and the CA, and injected the code executed on the client to complete the entire process. This process looks to the user as if it complies with the ACME protocol.

Sorry for my misunderstanding, I tried to read the donation and get your worried about acme.sh provides RCE convenience.

**Comment by xiaohuilam** [comment]
> > I suggest you do less Irresponsible to blame an open source community
> 
> I'm just raising my concerns, not blaming anyone. You also said that you are not a CA organization, but "hijacked" the interaction between the user and the CA, and injected the code executed on the client to complete the entire process. This process looks to the user as if it complies with the ACME protocol.

This isn't a hijacking behavior.
Because reseller is a wildly accepted in TLS industry.
All customer or free users let me to sign their CSR, i will DO ask they to create a DNS record or DNS challenge or upload a file for HTTP challange, if further this topic there is also E-mail validation which i trigger CA to send.
So by i mean, the automation file uploading isn't hijacking.

**Comment by iammeken** [comment]
> Confusingly, they donated $1000 to acme.sh in 2022. （[see here](https://github.com/acmesh-official/acme.sh/issues/4659#issuecomment-1584414218)）
> So it is puzzling whether this vulnerability is intentionally not fixed

**Comment by xiaohuilam** [comment]
> > Confusingly, they donated $1000 to acme.sh in 2022. （[see here](https://github.com/acmesh-official/acme.sh/issues/4659#issuecomment-1584414218)）
> > So it is puzzling whether this vulnerability is intentionally not fixed
> 
> Other parts are off-topic (from this issue), please discuss them somewhere else.
> 
> I want to know the answer to this quoted. Please, @Neilpang

I replied at my [comment](https://github.com/acmesh-official/acme.sh/issues/4668#issuecomment-1585616489) in the section `Question-2`.

**Comment by iammeken** [comment]
> > > Confusingly, they donated $1000 to acme.sh in 2022. （[see here](https://github.com/acmesh-official/acme.sh/issues/4659#issuecomment-1584414218)）
> > > So it is puzzling whether this vulnerability is intentionally not fixed
> > 
> > 
> > Other parts are off-topic (from this issue), please discuss them somewhere else.
> > I want to know the answer to this quoted. Please, @Neilpang
> 
> I replied at my [comment](https://github.com/acmesh-official/acme.sh/issues/4668#issuecomment-1585616489) in the section `Question-2`.

Thanks, but you are not @Neilpang, right?

I want the answer from @Neilpang, thanks.

**Comment by Neilpang** [comment]
@iammeken 

Sorry, I'm traveling abroad now.
I didn't know this particular vulnerability issue,  but I knew they are using acme.sh to show QR code and do some payments. they provided more free wildcard certs options to the community, which I was happy to see. (I didn't use their service, I switched all my certs to Zerossl long time ago).  Everytime a new ACME CA joined the community, I was very happy.

acme.sh does not strictly process the response from the CA server, it's one of the complains from the beginning, but I think it's hard to utilize, because you have to own a public trusted CA.  no such bad ca was reported before. I don't think a public trusted CA can afford the risks.  So I preferred to TRUST the response from a trusted CA.

So,  it looks to me not that urgent, It's on my plan to filter the response, but  I was very very busy with other personal stuffs recently. I had only a little time on this project. I had a new job to travel abroad, and a small daughter. I'm enjoying the time with my family.

On the other hand,  I appreciate the donations from all the supporters, including this HiCA guy(They donated much ealier than I ever heard about their CA)

It's all my fault to write this buggy code. I was never intentionally to write broken code. I was not that actively revewing code.

Anyway,  you are resonable to blame on me.  It's my fault.

The code was fixed and new relase was out.

As the impact of this bug, only when you used the HiCA could be affected. I don't think there are many users using this ca, If you use other CAs, there are no risks I think.

I'm going to close this issue,  If there is any more bugs found, please just let me know. 

I will give more focus on new CAs in future, I will try my best.

My apologies to all of you.

**Comment by mholt** [comment]
@BeSafee I am 100% convinced there is no collusion between HiCA and acme.sh. My belief is that @xiaohuilam found an opportunity and took it, without full disclosure.

Like you, @Neilpang -- speaking as another ACME client developer -- I would have assumed we could trust responses from the CA. If a user configures a CA, it means they trust it. I don't think this is your fault.

You're doing good work, and we are thankful for your volunteer efforts to maintain a project that positively benefits the security of the Web.

@xiaohuilam Thank you for having the discussion. Realizing there is a language barrier that is probably frustrating, your ongoing cooperation is appreciated.

**Comment by xiaohuilam** [comment]
> @BeSafee I am 100% convinced there is no collusion between HiCA and acme.sh. My belief is that @xiaohuilam found an opportunity and took it, without full disclosure. Please assume good faith on the part of the developer.
> 
> Like you, @Neilpang -- speaking as another ACME client developer -- I would have assumed we could trust responses from the CA. If a user configures a CA, it means they trust it. I don't think this is your fault.
> 
> You're doing good work, and we are thankful for your volunteer efforts to maintain a project that positively benefits the security of the Web. If users -- particularly businesses -- need assurances that the code is safe, they can sponsor you for it (and pay for a proper audit).
> 
> @xiaohuilam Thank you for having the discussion. Realizing there is a language barrier that is probably frustrating, your ongoing cooperation is appreciated.

Thank you @mholt, you teach our company and the community how the importance of the cyber security.
My team will keep actively to do more research in ACME ecosystem and this time we won’t treat all weak point as trade secrets, but will disclose fully in the future.
Very sorry to @Neilpang for the RCE influences, hope we can contribute the community developing and share more informations publicly in the future.

Best regards to the acme.sh community, and hope more entrepreneurs in the industry can do more support to the community.
