### ISSUE TITLE
Gandi Live DNS Depricated

### ISSUE THREAD

**Issue by FreakyBigFoot** [acmesh-official/acme.sh#4836]
Gandi has deprecated the live DNS API Keys. Is there another method planned to be able to accomplish DNS checks?

**Comment by Neilpang** [comment]
Is there any announcement ?

**Comment by FreakyBigFoot** [comment]
They deprecated the API and now use an application key. Since this change has occurred it seems it's no longer possible to renew certificates.

**Comment by helix-loop** [comment]
The announcement for the deprecation of DNS API Keys in favor of Personal Access Tokens is here: https://docs.gandi.net/en/account_management/security/developer_access.html

The description of PAT is here: https://docs.gandi.net/en/managing_an_organization/organizations/personal_access_token.html

I also had problems to renew certificates via DNS API Keys and had to renew manually, because neither DNS API Keys nor PAT are working with acme.sh at the moment.

I found this issue and the file where I expect Gandi LiveDNS API to be handled within acme.sh: 

https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_gandi_livedns.sh

There is the following line defining the API URL:
GANDI_LIVEDNS_API="https://dns.api.gandi.net/api/v5" 

However this URL is "https://api.gandi.net/v5/livedns" according to https://api.gandi.net/docs/livedns/

Should the URL be changed to support Gandi LiveDNS API again in acme.sh?
