### ISSUE TITLE
Token and other secret security

### ISSUE THREAD

**Issue by clauderobi** [acmesh-official/acme.sh#4952]
I see that the API token (for DNS but most likely for anything) are stored in account.conf. 

This is highly insecure. Is it possible to globally force acme.sh to NOT store anything that is sensible? I mean storing API keys, particularly for DNS, is a big no!!! Ypu might as well give your site to the world!

**Comment by Neilpang** [comment]
if the api key is not saved,  how can I renew the cert automatically.

**Comment by clauderobi** [comment]
Well, instead of storing the key in a plain text file, may be provide the ability to inject the API token by another mean. That other mean could then manage it better than a plain text file.

**Comment by GamerBene19** [comment]
I have similar concerns. Imo storing sensitive stuff like API-Keys on disk (especially considering #739) is bad design.

> if the api key is not saved, how can I renew the cert automatically.

I think one option would be to require the necessary environment variables (e.g. `CF_Token`) to be set when the script is executed. It can then be up to the user to provide the token (e.g. via docker, reading it from a (non world-readable) .env file, by manually providing it at runtime, ...).

I'm no security expert, so I can't say if this is the "best" approach, but imo it is better than storing the values on disk)

A workaround that seems to work (at least for cloudflare and at least for now): 
1. Delete the token from `acme.sh/account.conf` (e.g. put `SAVED_CF_Token=''`) after having issued a certificate
2. Make sure you have the necessary environment variable(s) set at runtime (e.g. via docker (compose))

This seems to work since environment variables take priority over stored config values.
