### ISSUE TITLE
acme-acmesh 3.0.7-1 not working on OpenWrt 23.05.2

### ISSUE THREAD

**Issue by jze2** [acmesh-official/acme.sh#5045]
# cat /etc/config/acme 

config acme
	option account_email '<<MY EMAIL>>'
	option debug '1'

config cert '<<MY CN>>'
	option enabled '1'
	option use_staging '0'
	option keylength '2048'
	list domains '<<MY CN>>'
	option update_uhttpd '1'
	option validation_method 'standalone'

# /etc/init.d/acme start
acme: added nft rule: handle 302
acme-acmesh: Running ACME for <<MY CN>>
/usr/lib/acme/hook: line 121: standalone: parameter not set
acme: cleaning up

**Comment by chandave** [comment]
I believe your issue is with setting up acme.sh for openwrt, not raw acme.sh execution.

Your /etc/config/acme looks uninitialized.

Have you went through the procedures in:
https://openwrt.org/docs/guide-user/services/tls/acmesh

Just a quick glance:

1. 'account_email' not defined yet
2. cert not named yet
3. 'list domains' doesn't have any DNS domains/hostnames defined

I would strongly suggest you read the document for setting up acme.sh inside openwrt. If you have problems with setting up openwrt to use acme.sh, then a better forum for your questions would be:
https://forum.openwrt.org

If everything is setup properly on the openwrt side and you still have problems with acme.sh, then I would suggest you run acme.sh from the command line (CLI) via an SSH login into your openwrt device. From the CLI, you can issue the '--debug 2' option and get the logs necessary to obtain help from this Github issues tracking system.

Good Luck!

Regards,

Davy Chan

**Comment by jze2** [comment]
Thank you for your time. The configuration file is initialized, I just redacted the actual values and formatting of the port removed them :-( 

I followed the "More easier way by using GUI" steps from openwrt.og. Nothing happened. I also tried steps in "Standalone Mode Validation" - moved uhttpd to port 8080 and enabled port 80 on firewall. No effect.

Starting the service via GUI results in the same output. The crontab also contains `/etc/init.d/acme start`.

**Comment by chandave** [comment]
Looking at your error message:
/usr/lib/acme/hook: line 121: standalone: parameter not set

It seems like there's an issue with the openwrt /usr/lib/acme/hook file. I don't think it has even gotten to starting up the acme.sh shell script.

Check your openwrt system logs to see if acme.sh even started.

Try SSH'ing into the openwrt device and running acme.sh (with all the proper command line options) to see if it works properly.

In any case, it would be best to ask the openwrt forum. This is an issue with how they packaged and implement their support for acme.sh. I don't see anything pointing to an issue with the original acme.sh.

Sorry I can't be of more help. I use openwrt but not v23.05.x and not running acme.sh on it.

Good luck.

Davy Chan

**Comment by user8446** [comment]
This issue is now fixed [here](https://github.com/openwrt/packages/issues/23756)
